site_name: Ansible Microk8s
site_url: https://IanTeda.github.io/ansible-microk8s
theme:
  name: material
nav:
    - Home: index.md
    - Users: users.md
    - Nodes: nodes.md
    - Microk8s:
      - Install: install.md
      - Update: update.md
      - Reset: reset.md
      - Uninstall: uninstall.md