# Update and install Ubuntu packages
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
---
- name: Update apt sources
  ansible.builtin.apt: 
    name: aptitude 
    update_cache: yes 
    state: latest 
    force_apt_get: yes

- name: Upgrade the OS (apt-get dist-upgrade)
  ansible.builtin.apt: 
    upgrade: dist

- name: Update installed packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Install required packages
  ansible.builtin.apt: 
    name: "{{ APT_PACKAGES }}"
    state: latest
    autoclean: yes
    autoremove: yes
    